// <auto-generated />
using System;
using DevIO.Data.context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DevIO.Data.Migrations
{
    [DbContext(typeof(GSProDbContext))]
    [Migration("20200330073415_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DevIO.Bussines.models.Siati", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacaoProcesso")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomeProcesso")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NomeUser")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NumeroProcesso")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Resolucao")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("Resolvido")
                        .HasColumnType("bit");

                    b.Property<string>("TipoProcesso")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Siatis");
                });
#pragma warning restore 612, 618
        }
    }
}
